# Generated by Django 2.1.2 on 2019-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
