# Generated by Django 2.1.2 on 2019-02-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0003_auto_20190228_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetaskinfo',
            name='base_ip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagetaskinfo',
            name='test_ip',
            field=models.CharField(default='', max_length=50),
        ),
    ]
