# Generated by Django 2.1.2 on 2019-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0004_auto_20190228_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
