# Generated by Django 2.1.2 on 2019-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0005_auto_20190228_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetaskinfo',
            name='port_from',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagetaskinfo',
            name='port_to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
