# Generated by Django 2.1.2 on 2019-03-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0007_auto_20190301_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
