# Generated by Django 2.1.2 on 2019-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0008_auto_20190303_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='end_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='start_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
