# Generated by Django 2.1.2 on 2019-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0009_auto_20190305_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultinfo',
            name='filename',
            field=models.CharField(default='', max_length=500),
        ),
    ]
