# Generated by Django 2.1.2 on 2019-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0011_auto_20190307_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaskinfo',
            name='svPath',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
