# Generated by Django 2.1.2 on 2019-03-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picEval', '0012_auto_20190315_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetaskinfo',
            name='port_from',
        ),
        migrations.RemoveField(
            model_name='imagetaskinfo',
            name='port_to',
        ),
    ]
